# ====== Settings for DeathControl ======
# IMPORTANT: Do NOT use tabs in this file! Only use spaces!
# 
# Documentation about how to set up this configuration can be found here:
# http://dev.bukkit.org/server-mods/deathcontrol/pages/configuration/


use-bukkit-permissions: true
logging-level: standard
