# ====== Settings for DeathControl ======
# IMPORTANT: Do NOT use tabs in this file! Only use spaces!
# 
# Documentation on how to set up this configuration can be found here:
# http://dev.bukkit.org/server-mods/deathcontrol/pages/configuration/


disable-permissions: false
logging-level: standard

multi-world:
    allow-cross-world: true
    disabled-worlds: []
